<?php 

use AngularComponent\Core\Behavior;
use \AngularComponent\Form\Image;
use AngularComponent\Panel\Container;
use AngularComponent\Storage\ExternalJsonStorage;

$global = new Container();
$global->addChild($container = new Container());


$container->addChild($c = new Container());
$container->addAttribute("style","height: 600px");
$global->getController()->addChild(new Behavior('$scope.slides={}'));
$global->getController()->addChild(new Behavior('$scope.slides.data=["0.jpg","1.jpg","10.jpg","11.jpg","12.jpg","13.jpg","14.jpg","15.jpg","16.jpg","17.jpg","18.jpg","19.jpg","2.jpg","20.jpg","21.jpg","22.jpg","23.jpg","24.jpg","25.jpg","26.jpg","27.jpg","28.jpg","29.jpg","3.jpg","30.jpg","31.jpg","32.jpg","33.jpg","34.jpg","35.jpg","36.jpg","37.jpg","4.jpg","5.jpg","6.jpg","7.jpg","8.jpg","9.jpg","IMG_0376-1.jpg","IMG_0388-1.jpg","IMG_0395-1.jpg","IMG_0397-1.jpg","IMG_0398-1.jpg","IMG_0399-1.jpg","IMG_0403-1.jpg","IMG_0404-1.jpg","IMG_0410-1.jpg","IMG_0411-1.jpg","IMG_0414-1.jpg"]'));
//$c->getController()->addChild($slides            = new ExternalJsonStorage('slides','/shower/index/images'));

$c->setDom('carousel');
$c->addAttribute('interval', '5000');
$c->addChild($s = new Container()) ;
$s->setDom('slide');
$s->addAttribute('ng-repeat', 'slide in slides.data');
$s->addChild($image = new Image('/img/shoot/[[slide]]'));



\AngularComponent\Renderer::i()->show($global);
