<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('PariMail Responsive, Social & Incredible WebMail')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script id="angularScript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.7/angular.js"></script>
        <script src="http://web.waste.email/public/js/ckeditor/ckeditor.js"></script>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'))
                        ->prependStylesheet($this->basePath() . '/css/loading-bar.css')
                        ->prependStylesheet($this->basePath() . '/css/parimail.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        
                        
                        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/loading-bar.js')
            ->prependFile($this->basePath() . '/js/ui-bootstrap-tpls-0.11.0.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap-typeahead.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51566313-1', 'parimail.fr');
  ga('send', 'pageview');

</script>
    </head>
    <body>
        <a href="https://github.com/Darkapus/PariMail" target="_blank"><img src="http://www.baschet.fr/img/forkme_right_darkblue.png" class="pm-logo"/></a>
        
        <div class="panel-heading text-center">
            <h1 class="text-muted"><img src="https://insight.sensiolabs.com/projects/263f62dc-ffb9-4039-b144-d7e680f5e2d5/big.png" /> PariMail</h1>
            <h5 class="text-muted">Responsive, Social & Incredible WebMail</h5>
        </div>
        
        
    <?php
    if(!Mailer\Model\Auth::i()->getEmail()){
    	
    ?>
    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src="http://www.uitech.me/img/logo.png" width="30px"/></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active ">
                <a href="/">Home</a>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Product <b class="caret"></b></a>
                <ul class="dropdown-menu">
                <li class="dropdown-submenu"><a href="#">AngularComponent</a>
                	<ul class="dropdown-menu">
                		<li><a href="#">Download</a></li>
                		<li><a href="#">Documentation</a></li>
                	</ul>
                </li>
                <li class="dropdown-submenu"><a href="#">PariMail</a>
                	<ul class="dropdown-menu">
                		<li><a href="#">Download</a></li>
                		<li><a href="#">Documentation</a></li>
                	</ul>
                </li>
              </ul>
            </li>
            
            
            
            
          
          </ul>
          
          
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Customer <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#"  data-toggle="modal" data-target="#ModalConnect">Connect</a></li>
                <li><a href="/auth/signup">Sign up</a></li>
                <li class="divider"></li>
                <li><a href="/contract">Contract</a></li>
                
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <?php
    }
    ?>

        
            <?php echo $this->content; ?>
            
        
        <?php echo $this->inlineScript() ?>
        
    
	<div class="panel-footer">
      <div class="container">
        <p class="text-muted">
                © 2014 <a href="http://www.parimail.fr/" target="_blank" title="parimail.fr">
        		parimail.fr        </a>        
                <span class="sep"> | </span>		 
        		Powered by : 
        		<a href="https://angularjs.org/" target="_blank">AngularJs</a>, 
        		<a href="http://framework.zend.com/" target="_blank">Zend 2</a>, 
        		<a href="http://www.doctrine-project.org/" target="_blank">Doctrine 2</a>, 
        		<a href="https://github.com/Darkapus" target="_blank">AngularComponent</a>, 
        		<a href="http://www.elasticsearch.org/" target="_blank">ElastikSearch</a>, 
        		<a href="http://getbootstrap.com/" target="_blank">Bootstrap</a>, 
        		<a href="http://ckeditor.com/" target="_blank">CKEditor</a>, 
            </p>
      </div>
    </div>

	<script>
    jQuery(document).ready(function($) {
    	var $filter = $(' .navbar-static-top');
    	var $logo = $('.pm-logo');
    	var $filterSpacer = $('<div />', {
    		"class": "filter-drop-spacer",
    		"height": $filter.outerHeight()
    	});
    
    
    
        
    	if ($filter.size())
    	{
    		$(window).scroll(function ()
    		{
    			if (!$filter.hasClass('navbar-fixed-top') && $(window).scrollTop() > $filter.offset().top)
    			{
    				$filter.before($filterSpacer);
    				$filter.addClass("navbar-fixed-top");
    				$logo.addClass("fix");
    			}
    			else if ($filter.hasClass('navbar-fixed-top')  && $(window).scrollTop() < $filterSpacer.offset().top)
    			{
    				$filter.removeClass("navbar-fixed-top");
    				$logo.removeClass("fix");
    				$filterSpacer.remove();
    			}
    		});
    	}
    
    
        $('#connecter').click(function(){
            $.ajax({url: '/mailer/index/connect', dataType: 'json', type:"POST",data: {email: $('#email').val(),password: $('#password').val()} }).success(function(data){
                if(data.success==true){
                    location.href = data.url;
                }
            
            });
        })
    });
	</script>
	

<!-- Modal -->
<div class="modal fade" id="ModalConnect" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <form class="form-signin" role="form" method="post">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Connect It</h4>
          </div>
          <div class="modal-body">
            
                <h2 class="form-signin-heading">Please sign in</h2>
                <input type="email" id="email" class="form-control" placeholder="Email address" required autofocus>
                <input type="password" id="password" class="form-control" placeholder="Password" required>
                <label class="checkbox">
                  <input type="checkbox" value="remember-me"> Remember me
                </label>
                
              
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" id="connecter">Connect</button>
          </div>
      </form>
    </div>
  </div>
</div>

    </body>
</html>